# volumes 成功，不過改資料後，還需重啟 service 才會改變
version: '3'
services:
  nuxt:
    image: node:lts
    command: npm run start-docker
    container_name: nuxt
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
  server:
    image: nginx:alpine
    container_name: nuxt_nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
